# Generated by Django 5.2.10 on 2026-02-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
