# Generated by Django 5.2.10 on 2026-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_candidate_interview_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='disqualification_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
    ]
