# Generated by Django 5.2.1 on 2026-03-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_disqualification_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
